### PR TITLE
Install matplotlib from pip

### LINKED ISSUE #103: Error: No available formula with the name "homebrew/science/matplotlib"
On `./install`
```
Error: No available formula with the name "homebrew/science/matplotlib" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/science is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/science)" fetch --unshallow

homebrew/science/matplotlib was deleted from homebrew/science in commit 224eed91:
  Deprecate Homebrew/homebrew-science (https://github.com/Homebrew/homebrew-science/issues/6616)

To show the formula before removal run:
  git -C "$(brew --repo homebrew/science)" show 224eed91^:matplotlib.rb

If you still use this formula consider creating your own tap:
  https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html
ERROR: the following rosdeps failed to install
  homebrew: command [brew install homebrew/science/matplotlib] failed

```

### PR DESCRIPTION
**Pull request by Caramelle**
Fixes #103

### CODE REVIEW

**Comment by kdhansen** [comment]
This is essentially a duplicate of the key for matplotlib in the rosdistro/rosdep/osx-homebrew.yaml. I would just remove the local key from ros-install-osx.

The reason for using Homebrew in the first place, was to have it bottled to reduce build time. That is not an option anymore.

**Comment by NikolausDemmel** [comment]
What about installing it from brewsci/science? 
https://github.com/mikepurvis/ros-install-osx/issues/103#issuecomment-360119371

**Comment by NikolausDemmel** [comment]
Actually, with brewed matplotlib from brewsci, e.g. rqt_bag errors when starting:

```
rqt_bag
^[[ARosPluginProvider.load(rqt_bag_plugins/BagPlotPlugin) exception raised in __builtin__.__import__(rqt_bag_plugins.plot_plugin, [PlotPlugin]):
Traceback (most recent call last):
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_gui/ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_bag_plugins/plot_plugin.py", line 35, in <module>
    from .plot_view import PlotView
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_bag_plugins/plot_view.py", line 77, in <module>
    from rqt_plot.data_plot import DataPlot
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_plot/data_plot/__init__.py", line 49, in <module>
    from .mat_data_plot import MatDataPlot
  File "/opt/ros/lunar/lib/python2.7/site-packages/rqt_plot/data_plot/mat_data_plot.py", line 53, in <module>
    import matplotlib
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1131, in <module>
    rcParams = rc_params()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 975, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1100, in rc_params_from_file
    config_from_file = _rc_params_in_file(fname, fail_on_error)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1018, in _rc_params_in_file
    with _open_file_or_url(fname) as fd:
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1000, in _open_file_or_url
    encoding = locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 545, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 477, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

rqt_bag.TimelineFrame.load_plugins() failed to load plugin "rqt_bag_plugins/BagPlotPlugin":
unknown locale: UTF-8
```

Removing that and installing from pip works. Also, installing from pip (at least for me) used a precompiled wheel, so it was super quick to install.

**Comment by NikolausDemmel** [comment]
So: +1

**Pull request merged**
