### PR TITLE
[WIP] Test install script on travis

### PR DESCRIPTION
**Pull request by wkentaro**
## Demo
https://github.com/wkentaro/ros-install-osx/pull/1

### CODE REVIEW

**Comment by mikepurvis** [comment]
Thanks for taking a look at this! I did a little bit of experimenting with it here:

https://github.com/wjwwood/serial/pull/104/files

I found that the build was extremely slow on virtualized OSX, and I bumped up against Travis's time limits before I really even got started:

https://travis-ci.org/wjwwood/serial/builds/71954025

I think to realistically CI this, we'd be looking at a home-grown solution that runs natively on an OS X Jenkins machine somewhere— it would basically just run one job at once, zap its Homebrew install between runs, and maybe have a squid cache in front of the bintray URLs.

**Comment by wkentaro** [comment]
Thank you for managing this awesome project!
I successfully installed ROS indigo on OS X Elcapitan, with my Macbook Pro at this time. (rviz, perception packages, gazebo works properly)

As you said, I find the build is slow (brew install opencv failed because of 10 minutes timeout: https://travis-ci.org/wkentaro/ros-install-osx/builds/125465759)

> I think to realistically CI this, we'd be looking at a home-grown solution that runs natively on an OS X Jenkins machine somewhere— it would basically just run one job at once, zap its Homebrew install between runs, and maybe have a squid cache in front of the bintray URLs.

That sounds nice.

**Comment by mikepurvis** [comment]
Another way would be to repackage ros-install-osx as a singular homebrew formula (ros-indigo-desktop-full-bundle, or something), and contributing it to homebrew-science, so that Homebrew themselves test and bottle it— this would be cadillac solution, since then anyone could trivially set up ROS on a Mac. But to get there, we'd have to be in a place where everything that it depends on is bottled (gazebo), and the options included in the bottled version work for us (opencv).

If you or others are interested, I'd be delighted to see progress on getting Gazebo into homebrew-science and getting the default options for opencv changed.

Another nice thing about doing an all-in-one formula is that we could sidestep some of the nuisances with rosdep (for example, we can depend on the python-numpy homebrew formula and get a bottle, rather than installing it from pip and ending up having to build it each time).

**Comment by mikepurvis** [comment]
Covered by #49.

**Pull request closed without merging**
